import React from "react";
import Head from "next/head";
import PageContent from "../../../components/layout/PageContent";
import NewPostForm from "../../../components/Posts/NewPostForm";
import About from "../../../components/community/About";
import { Flex, Box, Icon, Image, Text, Button } from "@chakra-ui/react";
import { auth } from "../../../firebase/clientApp";
import useCommunityData from "../../../hooks/useCommunityData";
import { useAuthState } from "react-firebase-hooks/auth";
import { communityState } from "../../../atoms/communitiesAtom";
import { useRecoilValue } from "recoil";

const SubmitPostPage: React.FC = () => {
	//const communityStateValue = useRecoilValue
	const { communityStateValue } = useCommunityData();
	const [user] = useAuthState(auth);

	return (
		<>
			<Head>
				<title>Post on Reddit</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="https://www.iconpacks.net/icons/2/free-reddit-logo-icon-2436-thumb.png"
				/>
			</Head>
			<PageContent>
				<>
					<Box
						p="14px 0px"
						borderBottom="1px solid"
						borderColor="white"
					>
						<Text>Create a Post</Text>
					</Box>
					{user && (
						<NewPostForm
							user={user}
							communityImageURL={
								communityStateValue.currentCommunity.imageURL
							}
							communityId={
								communityStateValue.currentCommunity.id
							}
						/>
					)}
				</>

				<>
					{communityStateValue.currentCommunity && (
						<About
							communityData={communityStateValue.currentCommunity}
						/>
					)}
				</>
			</PageContent>
		</>
	);
};

export default submitPostPage;
